#!/bin/bash

# ClaudyGod Security Setup Script
# Generates secure API keys and JWT secrets

set -e

echo "🔒 ClaudyGod Security Setup"
echo "=============================="
echo ""

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo "ℹ️  .env.local already exists. Backing up to .env.local.backup"
    cp .env.local .env.local.backup
fi

# Generate secure keys
echo "🔐 Generating secure keys..."
API_KEY_1=$(openssl rand -hex 32)
API_KEY_2=$(openssl rand -hex 32)
INTERNAL_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

# Create .env.local
cat > .env.local << ENVEOF
# Generated by setup-security.sh at $(date)
API_BASE_URL=http://localhost:8080
VALID_API_KEYS=${API_KEY_1},${API_KEY_2}
INTERNAL_API_KEY=${INTERNAL_KEY}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
NEXT_PUBLIC_API_KEY_REQUIRED=true
NEXT_PUBLIC_VIDEO_PROXY_ENABLED=true
ENVEOF

echo "✅ Environment file created: .env.local"
echo ""
echo "🔑 Security Keys Generated:"
echo "=============================="
echo ""
echo "API Key 1:      ${API_KEY_1}"
echo "API Key 2:      ${API_KEY_2}"
echo "Internal Key:   ${INTERNAL_KEY}"
echo "JWT Secret:     ${JWT_SECRET}"
echo ""
echo "⚠️  IMPORTANT:"
echo "  - Save these keys in a secure location"
echo "  - NEVER commit .env.local to git"
echo "  - Use different keys for production"
echo "  - Rotate keys every 90 days"
echo ""
echo "✨ Setup complete! You can now use:"
echo "   npm run dev"
